version: "3.7"

services: 
  web:
    container_name: nodecommerce
    restart: always
    build: .
    ports: 
      "3000:3000"
    links: 
      - mongo
    db:
      container_name: mongo
       image: mongo
       volumes: 
        - ./data:/data/db
    ports:
      - "$PORT:$PORT"