version: "3.7"

services: 
  web:
    image: nodedocker:dev
    build:
      context: .
      target: dev
    container_name: nodecommerce
    restart: always
    ports: 
      "3000:3000"
    volumes: 
      - .:/app
    depends_on:
      - nodecommerce
    environment:
      - dbURI=process.env.dbURI
      - GOOGLE_CLIENT_ID=process.env.GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET=process.env.GOOGLE_CLIENT_SECRET
      - SESSION_SECRET=process.env.SESSION_SECRET
      - CLOUD_NAME=process.env.CLOUD_NAME
      - API_KEY=process.env.API_KEY
      - API_SECRET=process.env.API_SECRET
      - PAYSTACK_SECRET=process.env.PAYSTACK_SECRET
      - PAYSTACK_PUBLIC=process.env.PAYSTACK_PUBLIC
      - SENGRID_API_KEY=process.env.SENGRID_API_KEY
    networks: 
      - nodecommerce-network


networks: 
  nodecommerce-network:
    name: nodecommerce-network